### ISSUE TITLE
ideviceinstaller.exe exception 

### ISSUE THREAD

**Issue by GF-Huang** [storoj/libimobiledevice-win32#10]
Hello storoj,

First of all, thank you for great project.

I just downloaded the project and open libimobiledevice-win32.sln with VS2012 Ultimate
I built with "Debug" and done.

I run with debug mode the "ideviceinstaller.exe" with args as the follow picture
![qq20130920001334](https://f.cloud.github.com/assets/4510984/1174358/761bf19e-2146-11e3-9da8-91fabb0d9264.png)

but it throw an untreated exception as follow picture.
![sad](https://f.cloud.github.com/assets/4510984/1174354/6670ee16-2146-11e3-82ff-6463fdf47c50.jpg)

I follow the call stack and find the source as follow picture
![qq20130920001512](https://f.cloud.github.com/assets/4510984/1174374/be6dfd70-2146-11e3-87ad-4c95ca7920ca.png)

Help me , please.
I debug it for six hours but have no evolve.

**Comment by storoj** [comment]
Im sorry, i cant realize what is the problem. May you send me your ipa? dark.storoj@gmail.com

**Comment by GF-Huang** [comment]
ok, I sent.  Thank you at first.

**Comment by GF-Huang** [comment]
Hello,  storoj ! 
I build it in Win7 x64.  Is  this problem related to x86 or x64 ?

**Comment by rayan99** [comment]
Hi storoj,
I also face exactly the same problem. Same File , Same Function, Same Error. Spent several hours before seeing this post.
Please let me know if you need any more details. Kindly help me in this.

**Comment by rayan99** [comment]
Found a fix for this. This is some problem with ziplib.lib. Downloaded zlib1.dll and placed it in the folder in which my .exe is present. I works fine now.

**Comment by rayan99** [comment]
Please use this link.
http://gnuwin32.sourceforge.net/packages/zlib.htm
Download the binaries zip file. The dll is in bin folder. 

If problem persists, then there may be issue with libxml2. try the below link.
http://sourceforge.net/projects/gnuwin32/files/libxml/2.4.12-1/libxml2-2.4.12-bin.zip/download

**Comment by GF-Huang** [comment]
ok, let me have a try first.
