### ISSUE TITLE
usbmuxd is not running

### ISSUE THREAD

**Issue by chideat** [storoj/libimobiledevice-win32#12]
i successfully build all the tools at debug module, but when i try to run any one of them, the same error always occured.

the error is :
usbmuxd_get_device_list: error opening socket! 
i can't find any usbmuxd serivce and target folder. 

thanks for your help!

**Comment by airwolf2026** [comment]
hi, 
in win32 
you should install apple mobile device service (include in itunes),
may help .

**Comment by chideat** [comment]
yes, it works. Thank you for your help.
I find that it may have some works to do with apple mobile device service and bonjour service.
