### ISSUE TITLE
Error in MobileSync_client_new

### ISSUE THREAD

**Issue by akhilritu** [storoj/libimobiledevice-win32#15]
i Build this project on windows successfully and access mobilesync.h to get all contact in my iphone but when i run the code i get error in following module.
mobilesync_error_t mobilesync_client_new(idevice_t device, lockdownd_service_descriptor_t service,
                           mobilesync_client_t \* client)
{
    if (!device || service->port == 0 || !client || *client)
        return MOBILESYNC_E_INVALID_ARG;

```
device_link_service_client_t dlclient = NULL;
mobilesync_error_t ret = mobilesync_error(device_link_service_client_new(device, service, &dlclient));
if (ret != MOBILESYNC_E_SUCCESS) {
    return ret;
}
```

my code exit from here with error ret= -3

please help me to solve the problem.

**Comment by akhilritu** [comment]
More information:
In the function:
 device_link_service_error_t device_link_service_client_new(idevice_t device, lockdownd_service_descriptor_t service, device_link_service_client_t *client)

property_list_service_client_t plistclient = NULL;
if (property_list_service_client_new(device, service, &plistclient) != PROPERTY_LIST_SERVICE_E_SUCCESS) {
        return DEVICE_LINK_SERVICE_E_MUX_ERROR;
    }
this is the error more specifically.
please help me to solve the problem.

**Comment by chauhanakhil** [comment]
i am facing the same problem in this:
if (property_list_service_client_new(device, service, &plistclient) != PROPERTY_LIST_SERVICE_E_SUCCESS) {
        return DEVICE_LINK_SERVICE_E_MUX_ERROR;
    }
please help.
