### ISSUE TITLE
Release mode showing lot of error 

### ISSUE THREAD

**Issue by vipinbeni** [storoj/libimobiledevice-win32#27]
Can any one solved it out to run this library in release mode  please help ..

**Comment by pizixie** [comment]
you can go to bitbucket and search by "libimobiledevice".
it build with vs2013
https://bitbucket.org/Vitallium/libimobiledevice-win32

**Comment by vipinbeni** [comment]
Hi i am getting error in below line 
This device isn't eligible for the requested build.
in following statement
response = tss_send_request(request, client->tss_url);

Kindly help me as i run same ispw file from itunes and it restore successfully .Kindly please tell me step how can i restore my device using idevicerestor module 

thanks
vipin

**Comment by pizixie** [comment]
sorry,i don't often use the idevicerestore.i don't know how to solve it.
