### ISSUE TITLE
want to port idevicerestore,but a lot error.

### ISSUE THREAD

**Issue by airwolf2026** [storoj/libimobiledevice-win32#6]
im a newbie of c++,i want to run idevicerestore on win32,but when i build the project in vs2010,there a lot error.what i mistake?

Error   2   error C4430: missing type specifier - int assumed. Note: C++ does not support default-int   e:\01.work\study\libmobiledeviceonwin32\libimobiledevice-win32-master\libimobiledevice-tools\idevicerestore\src\common.h    26  1   idevicerestore
Error   15  error C4430: missing type specifier - int assumed. Note: C++ does not support default-int   e:\01.work\study\libmobiledeviceonwin32\libimobiledevice-win32-master\libimobiledevice-tools\idevicerestore\src\common.h    26  1   idevicerestore
Error   48  error C4430: missing type specifier - int assumed. Note: C++ does not support default-int   e:\01.work\study\libmobiledeviceonwin32\libimobiledevice-win32-master\libimobiledevice-tools\idevicerestore\src\common.h    26  1   idevicerestore
Error   50  error C4430: missing type specifier - int assumed. Note: C++ does not support default-int   e:\01.work\study\libmobiledeviceonwin32\libimobiledevice-win32-master\libimobiledevice-tools\idevicerestore\src\ipsw.h  26  1   idevicerestore
Error   52  error C4430: missing type specifier - int assumed. Note: C++ does not support default-int   e:\01.work\study\libmobiledeviceonwin32\libimobiledevice-win32-master\libzip\zipconf.h  18  1   idevicerestore
Error   54  error C4430: missing type specifier - int assumed. Note: C++ does not support default-int   e:\01.work\study\libmobiledeviceonwin32\libimobiledevice-win32-master\libzip\zipconf.h  18  1   idevicerestore
Error   16  error C3861: 'recovery_send_ticket': identifier not found   e:\01.work\study\libmobiledeviceonwin32\libimobiledevice-win32-master\libimobiledevice-tools\idevicerestore\src\recovery.cpp    160 1   idevicerestore
Error   58  error C3861: 'recovery_enter_restore': identifier not found e:\01.work\study\libmobiledeviceonwin32\libimobiledevice-win32-master\libimobiledevice-tools\idevicerestore\src\idevicerestore.cpp  712 1   idevicerestore
Error   57  error C3861: 'get_nonce': identifier not found  e:\01.work\study\libmobiledeviceonwin32\libimobiledevice-win32-master\libimobiledevice-tools\idevicerestore\src\idevicerestore.cpp  667 1   idevicerestore
Error   56  error C3861: 'build_manifest_get_identity_count': identifier not found  e:\01.work\study\libmobiledeviceonwin32\libimobiledevice-win32-master\libimobiledevice-tools\idevicerestore\src\idevicerestore.cpp  524 1   idevicerestore
Error   55  error C3861: 'build_manifest_check_compatibility': identifier not found e:\01.work\study\libmobiledeviceonwin32\libimobiledevice-win32-master\libimobiledevice-tools\idevicerestore\src\idevicerestore.cpp  352 1   idevicerestore
Error   53  error C2371: 'int8_t' : redefinition; different basic types e:\01.work\study\libmobiledeviceonwin32\libimobiledevice-win32-master\libzip\zipconf.h  18  1   idevicerestore
Error   51  error C2146: syntax error : missing ';' before identifier 'zip_int8_t'  e:\01.work\study\libmobiledeviceonwin32\libimobiledevice-win32-master\libzip\zipconf.h  18  1   idevicerestore
Error   1   error C2144: syntax error : 'int' should be preceded by ';' e:\01.work\study\libmobiledeviceonwin32\libimobiledevice-win32-master\libimobiledevice-tools\idevicerestore\src\common.h    26  1   idevicerestore
Error   14  error C2144: syntax error : 'int' should be preceded by ';' e:\01.work\study\libmobiledeviceonwin32\libimobiledevice-win32-master\libimobiledevice-tools\idevicerestore\src\common.h    26  1   idevicerestore
Error   47  error C2144: syntax error : 'int' should be preceded by ';' e:\01.work\study\libmobiledeviceonwin32\libimobiledevice-win32-master\libimobiledevice-tools\idevicerestore\src\common.h    26  1   idevicerestore
Error   49  error C2144: syntax error : 'int' should be preceded by ';' e:\01.work\study\libmobiledeviceonwin32\libimobiledevice-win32-master\libimobiledevice-tools\idevicerestore\src\ipsw.h  26

thanks.

**Comment by storoj** [comment]
If you dont really want to use Visual Studio you may build all these libs and binaries using mingw or cygwin.
I had painless build with cygwin

Also i am trying to port idevicerestore

**Comment by airwolf2026** [comment]
Thank you for quick reply !
i'll try your suggest to build the project using mingw first.
BTW:the idevicerestore's code seem no up to date???

thanks again for you great work.

**Comment by vipinbeni** [comment]
Hi Sir ,

@airwolf2026  Can you port idevicerestore to this pls help me as i need this module.

**Comment by vipinbeni** [comment]
Hi Sir any update on idevicerestore on windows pls help me.

**Comment by vipinbeni** [comment]
@airwolf2026 Sir  have you implemented  this Restore module.
